### ISSUE TITLE
exporting images from Jupyter notebook

### ISSUE THREAD

**Issue by AlexLlanesQuevedo** [AlexLlanesQuevedo/santacruzi_project#5]
**I want to know how to export the figures resulting from the analysis with Jupyter notebook tools either to image formats or pdf.**
**For example, when I run tetrad and I get a figure like the one that appears at the bottom; however, it is not possible to export the figures to either image or pdf format**
![imagen](https://user-images.githubusercontent.com/59844946/98627352-aa93e980-22d9-11eb-8267-5299567aaad7.png)
![imagen](https://user-images.githubusercontent.com/59844946/98627308-8afcc100-22d9-11eb-9a8c-ca947e7bb2fe.png)

**Instructions for running tetrad in Jupyter notebook are available at: https://ipyrad.readthedocs.io/en/latest/API-analysis/cookbook-tetrad.html**
**I have reviewed web pages like https://medium.com/analytics-vidhya/export-images-from-jupyter-notebook-with-a-single-command-422db2b66e92, but I have not been able to apply it to my particular problem**

**Comment by IsauraRReinhold** [comment]
Maybe yo can trie this commands

```
plt.savefig('output.png', dpi=300, bbox_inches='tight')
```
```
fig.tight_layout()
plt.savefig('output.png', dpi=300)
```

**Comment by JavierUrban** [comment]
Example to export image in ipython notebook [https://stackoverflow.com/questions/29803224/saving-plot-from-ipython-notebook-produces-a-cut-image](https://stackoverflow.com/questions/29803224/saving-plot-from-ipython-notebook-produces-a-cut-image)

**Comment by solouli** [comment]
ipyrad gives you an option to save figures (eg. mrbayes). You can give it a look!

https://ipyrad.readthedocs.io/en/latest/API-analysis/cookbook-mrbayes.html?highlight=save#Save-figures

**Comment by IsauraRReinhold** [comment]
I found this solution

https://ipyrad.readthedocs.io/en/latest/API-analysis/cookbook-treemix.html#3.-Save-the-plot-to-pdf

**Comment by solouli** [comment]
Also if you have some trouble in the future saving multiple FIGURES from plots this could be a winner.

https://medium.com/analytics-vidhya/export-images-from-jupyter-notebook-with-a-single-command-422db2b66e92

**Comment by AlexLlanesQuevedo** [comment]
The problem was solved by adding the following lines to the notebook:


import toyplot.pdf
canvas, axes = mtre.draw_cloud_tree(
    width=400, height=300,
    html=True,
    edge_colors="red",
    tip_labels={i: i.rsplit("_", 1)[0] for i in mtre.treelist[0].get_tip_labels()}
);
toyplot.pdf.render(canvas, "./test1.pdf")


![imagen](https://user-images.githubusercontent.com/59844946/98693860-6be04c80-2336-11eb-8ea4-bce0f934984b.png)
