### ISSUE TITLE
Numbering the scripts

### ISSUE THREAD

**Issue by camillethuyentruong** [AlexLlanesQuevedo/santacruzi_project#7]
In [bin](https://github.com/AlexLlanesQuevedo/santacruzi_project/tree/master/bin), the scripts are numbered from number 2. Is there any reason not to have a script 1? Visitors to your repo might find it confusing and look for it.

Even though script 1 is simple, I suggest adding it so that your pipeline is complete, or at least mentioning it in the README.

**Comment by AlexLlanesQuevedo** [comment]
corrected!!!
