### ISSUE TITLE
Preliminary evaluation

### ISSUE THREAD

**Issue by camillethuyentruong** [AlexLlanesQuevedo/santacruzi_project#9]
**10% Organización del repositorio**
Folders need to be added for figures and results, with short descriptions in the general README

**15% README (debe ser en inglés)**
I suggest adding a small paragraph describing the objectives of your study and the type of data used (sequencing platform, number of samples).

The figure describing your pipeline contains a FastQC step at the beginning and an admixture analysis at the end that are both missing in your pipeline. Can you add them or at least mentioning them as "additional steps" or "in process" (so that the reader doesn't look for them as I did!) ?

**15% Análisis**
Clear and well-documented!

**15% Resumen y discusión en formato Markdown**
Missing so far.

**15% Gráfica(s) en R**
Missing so far. It would be good to have the [PCA-Structure.R](https://github.com/AlexLlanesQuevedo/santacruzi_project/blob/master/bin/PCA-Structure.R) script report in html or PDF to see the resulting graphics.

**15% Scripts deben estar comentados en inglés**
In [PCA-Structure.R](https://github.com/AlexLlanesQuevedo/santacruzi_project/blob/master/bin/PCA-Structure.R), the working directory need to be set to source file at the beginning of the script so that it is reproducible.

**15% Avances, organización y respuesta a comentarios en el proyecto de Github en inglés**
So far so good!

**Comment by solouli** [comment]
In addition to Camille's comments, I have some observations that I hope will help you to improve your repo:

- [ ] Add open-source license (https://choosealicense.com/)
- [ ] Add references in the Introduction
- [ ] Specify the name of the scripts used in each step (methodology diagram)
- [ ] It is not clear which is step 1. If it's quality analysis, specify it. 
- [ ] Specify what type of files are in data (eg Illumina MiSeq, Paired-End 300pb)

**Comment by AlexLlanesQuevedo** [comment]
Done! Thanks!!!!

**Comment by camillethuyentruong** [comment]
Nice and clear repo with well-documented scripts! I hope you enjoyed the course.

As mentioned above,  in [`5-PCA%26Structure.R`](https://github.com/AlexLlanesQuevedo/santacruzi_project/blob/master/bin/5-PCA%26Structure.R) (and in all yur future R scripts!) it is important to mention at the beginning that the working directory is to be set to source file so that the script is reproducible with relative routes.
